blog/authentication/urls.py
from django.urls import path
from . views import register
urlpatterns = [
    path('register',register,name='auth-register')
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('listings.urls')),
    path('__reload__',include('django_browser_reload.urls')),
    path('auth/',include('authentication.urls')),
    path('auth/',include('django.contrib.auth.urls'))

]

blog/listings/urls.py
from django.urls import path,include
from listings.views import home , create_blog , posts , blog_detail
from rest_framework.routers import SimpleRouter
from listings.views import PostApi

router =  SimpleRouter()

router.register('posts',PostApi,basename='api-posts')

urlpatterns = [
    path('home',home,name='blog-home'),
    path('posts/create/',create_blog,name='blog-post-create'),
    path('posts/',posts, name='blog-all-posts'),
    path('api/',include(router.urls)),
    path('posts/<int:id>',blog_detail,name='blog-detail')
]

blog/authentication/models.py
from django.db import models

# Create your models here.

blog/listings/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):

    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(default='none')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)


    def __str__(self):

        return self.title 

blog/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

input_class = "border text-2xl p-4 hover:outline-slate-500  focus:ring focus:ring-orange-200"

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

blog/listings/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ['title','description']

blog/authentication/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from . forms import RegisterForm

def register(request):

    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('blog-home')
        return render(request,form)


    return render(request,'authentication/register.html',{'form':form})

blog/listings/views.py
from django.shortcuts import render,redirect
from .forms import  PostForm
from .models import Post
from listings.serializer import PostSerializer
from rest_framework.viewsets import ModelViewSet

def home(request):

    return render(request,'listings/home.html')


def create_blog(request):

    if not request.user.is_authenticated:
        return redirect('blog-home')

    form = PostForm

    if request.method == "POST":

        form = PostForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            author = request.user
            Post.objects.create(title=title , description=description , author=author)
            return redirect('blog-home')
    return render(request,'listings/create.html',{'form':form})



def posts(request):

    posts = Post.objects.all()
    return render(request,'listings/blogs.html',{'post':posts})

def blog_detail(request,id):

    try:
        blog = Post.objects.get(id=id)
        calling = blog.author
        if blog.author == request.user:
            calling = "you"

    except :
        return redirect('blog-home')

    return render(request,'listings/detail.html',{'blog':blog,'calling':calling})

class PostApi(ModelViewSet):

    serializer_class = PostSerializer

    def get_queryset(self):
        
        return Post.objects.all()

blog/authentication/templates/authentication/register.html
{% extends 'listings/layout.html' %}

{% block content %}


<div class="container w-full flex flex-col items-center content-center m-4 gap-12">
    <p class="text-4xl text-slate-700 font-bold text-start ">Login Form</p> 
    <p class="text-3xl text-slate-500 font-normal"> Use your blog account</p>
    <form method="post" class="flex flex-col shadow gap-y-8 p-4">
        <input type="text" name="username" id="id_username" class="border text-2xl p-4 hover:outline-slate-500  focus:ring focus:ring-orange-200" placeholder="Enter your username">
        <input type="email" name="email" id="id_email" class="border text-2xl p-4 hover:outline-slate-500  focus:ring focus:ring-orange-200" placeholder="Enter your email">
        <input type="password" name="password1" id="id_password1" class="border text-2xl p-4 hover:outline-slate-500  focus:ring focus:ring-orange-200" placeholder="Type the password">
        <input type="password" name="password2" id="id_password2" class="border text-2xl p-4 hover:outline-slate-500  focus:ring focus:ring-orange-200" placeholder="Confirm the password">
        {% csrf_token %}
        <input type="submit" value="Login" class="text-2xl w-56 h-16 text-white rounded bg-orange-400 hover:bg-orange-500 font-mono px-12 py-4 cursor-pointer transition-colors ease-in-out">
    </form>
</div>


{% endblock %}

blog/listings/templates/listings/blogs.html
{% extends 'listings/layout.html' %}

{% block content %}

{% load static %}
<div class="container w-full flex flex-col items-center content-center m-4 gap-12">
    <p class="text-4xl text-slate-700 font-bold text-start "> What others people are sharing</p> 
    <div class="posts w-full mx-auto">
        {% for i in post %}
            <div class="row shadow">
                <img src="{% static 'listings/images/blog/blog.svg' %}" alt="">
                <h2 class="text-4xl text-slate-700">{{i.title }}</h2>
                <p class="text-3xl text-center">{{i.description }}</p>
                <a href="{% url 'blog-detail' i.id %}" class="text-3xl leading-none bg-orange-400 text-white px-12 py-4 hover:bg-orange-600">Read more</a>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

blog/listings/templates/listings/create.html
{% extends 'listings/layout.html' %}

{% block content %}


<div class="container w-full flex flex-col items-center content-center m-4 gap-12">
    <p class="text-4xl text-slate-700 font-bold text-start ">Create your blog here</p> 
    <form method="post" class="flex flex-col shadow gap-y-8 p-4">
        <input type="text" name="title" id="id_title" class="border text-2xl p-4 hover:outline-slate-500  focus:ring focus:ring-orange-200" placeholder="Enter the title">
        <textarea name="description" id="id_description" autocomplete="false" class="border text-2xl p-4 hover:outline-slate-500  focus:ring focus:ring-orange-200" placeholder="Description of the blog"></textarea>
        {% csrf_token %}
        <input type="submit" value="SAVE" class="text-2xl w-56 h-16 text-white rounded bg-orange-400 hover:bg-orange-500 font-mono px-12 py-4 cursor-pointer transition-colors ease-in-out">
    </form>
</div>


{% endblock %}

blog/listings/templates/listings/detail.html
{% extends 'listings/layout.html' %}

{% block content %}
    {% load static%}

    <div class="advice">
        <h2 class="text-6xl text-slate-800 text-center">This blog was written by {{calling}}</h2>
    </div>
    
    <div class="jumbotron shadow font-mono">
        <div class="text flex flex-col gap-12 justify-start ">
            <h2 class="text-6xl text-slate-800 uppercase">{{blog.title}}</h2>
            <p class="text-3xl lowercase">{{blog.description}}</p>
            <p class="text-3xl text-orange-600">written by {{calling}}</p>
        </div>
        <img src="{% static 'listings/images/blog/blog.svg' %}" alt="" class="image">
    </div>

    <a href="{% url 'blog-all-posts' %}" class ="text-2xl w-56 h-16 text-white rounded bg-orange-400 text-center hover:bg-orange-500 font-mono px-12 py-4 cursor-pointer transition-colors ease-in-out">Posts</a>

{% endblock %}

blog/listings/templates/listings/home.html
{% extends 'listings/layout.html' %}

{% block content %}
    {% load static%}
    
    <div class="jumbotron shadow font-mono">
        <div class="text flex flex-col gap-12 justify-start ">
            <h2 class="text-6xl text-slate-800 uppercase">Welcome to the blog</h2>
            <p class="text-3xl lowercase">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis numquam saepe at architecto, sequi eos reprehenderit similique accusamus hic autem, veritatis reiciendis repellendus. Neque assumenda, esse deserunt fugiat voluptatibus magni?</p>
            <button class="text-3xl bg-slate-800 text-center text-white rounded-sm  ">Read more</button>
        </div>
        <img src="{% static 'listings/images/blog/blog.svg' %}" alt="" class="image">
    </div>

    <div class="advice">
        <h2 class="text-6xl text-slate-800 text-center">Our Visitors are always happy!</h2>
    </div>

    <div class="choice gap-8">
        <div class="row border">
            <img src="{% static 'listings/images/read/read.svg' %}" alt="read-image">
            <p class="text-3xl lowercase">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis numquam saepe at architecto, sequi eos reprehenderit similique accusamus hic autem, veritatis reiciendis repellendus. Neque assumenda, esse deserunt fugiat voluptatibus magni?</p>
            <a href="{% url 'blog-post-create' %}" class="text-3xl bg-blue-500 text-center hover:bg-blue-800 text-white shadow-md rounded-sm  ">Create</a>
        </div>
        <div class="row border">
            <img src="{% static 'listings/images/article/article.svg' %}" alt="" >
            <p class="text-3xl lowercase">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis numquam saepe at architecto, sequi eos reprehenderit similique accusamus hic autem, veritatis reiciendis repellendus. Neque assumenda, esse deserunt fugiat voluptatibus magni?</p>
            <a href="{% url 'blog-all-posts' %}" class="text-3xl bg-blue-500 hover:bg-blue-800 shadow-md text-center text-white rounded-sm  ">Explore</a>
        </div>
    </div>

{% endblock %}

blog/listings/templates/listings/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to my blog</title>
    {% load tailwind_tags %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'listings/style.css' %}">
</head>
<body>
    {% tailwind_css %}
    
    <header class="header">
        <nav class="nav navbar bg-slate-800 px-6 py-8 flex flex-row justify-between w-full">
            <a href="{% url 'blog-home' %}" class="text-6xl text-white"> Gee<span class="text-orange-500 uppercase font-semibold">k</span>Blog </a>
            <ul class="flex flex-row gap-8">
                <li class="text-white text-4xl hover:text-orange-300 cursor-pointer transition-colors ease-linear"><a href="{% url 'blog-home' %}" >Blog</a></li>
                {% if request.user.is_authenticated %}
                    <li class="text-white text-4xl hover:text-orange-300 cursor-pointer transition-colors ease-linear"><a href="#" ></a>{{request.user}}</li>
                {% endif %}
                <li class="text-white text-4xl hover:text-orange-300 cursor-pointer transition-colors ease-linear"><a href="{% url 'login' %}">Login</a></li>
            </ul>
        </nav>
    </header>

    <main class="main mt-4 mb-4 flex flex-col justify-center items-center">
        {% block content%}
        {% endblock %}
    </main>

    <footer class="bg-slate-800 p-4">
        <p class="text-white text-3xl text-center">copyright 2022 &copy; kirikode 2022</p>
    </footer>

</body>
</html>

blog/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>